apiVersion: v1
kind: Service
metadata:
  name: {{ include "discovery-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "discovery-service.name" . }}
    helm.sh/chart: {{ include "discovery-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: prometheus-metrics
      port: 4321
      protocol: TCP
    - name: jmx
      port: 9010
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "discovery-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
