apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-api
  namespace: prometheus
  labels:
    app: kafka-api
    release: prometheus-operator
spec:
  endpoints:
    - interval: 30s
      path: /
      port: prometheus-metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    name: "event-log-service"
