apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kafka-api.name" . }}
    helm.sh/chart: {{ include "kafka-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kafka-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kafka-api.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9010
            - containerPort: 8182
            - containerPort: 4321
          readinessProbe:
            tcpSocket:
              port: 9010
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9010
            initialDelaySeconds: 20
            periodSeconds: 60
          env:
            - name: EVTL_CS_KEYSPACE
              value: "{{ .Values.eventLog.cassandra.cluster.keyspace}}"

          resources:
    {{- toYaml .Values.resources | nindent 22 }}
    {{- with .Values.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
    affinity:
    {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
    {{- toYaml . | nindent 8 }}
    {{- end }}